site_name: QA Automation Starter for Python
site_description: A starter project for QA Automation using pytest and Allure.
site_url: https://qa-automation-starter.github.io/qa-automation-python/
use_directory_urls: true

theme:
  name: material

plugins:
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:              # <<< missing bit
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight
  - codehilite:
      guess_lang: false
      use_pygments: true

nav:
  - Github Repo: https://github.com/QA-Automation-Starter/qa-automation-python?tab=readme-ov-file#readme
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Example Tests: example-tests.md
  - Example Allure Report: reports/index.html


